AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
